check:
  global:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
reporting:
  watermarks:
    statements: [75, 95]
    lines: [75, 95]
    functions: [75, 95]
    branches: [75, 95]