name: Deploy to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - master


env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build_pack_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run buildpackage
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os}}-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci && npm run test
      - name: Upload coverage to codecov
        if: always()
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
