name: Deploy to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - master


env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build_pack_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm publish
