name: Test Package

on:
  pull_request:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run test
      - run: npm run cover
        if: always()
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files:
            test-results/**.xml
      - name: Upload to codecov
        if: always()
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}